"""
ftrack Credentials Configuration

Manages ftrack credentials with graphical interface.
Saves to .env file in config/ folder

NOTE: Load/save credential functions can be used without PySide6.
      Only the GUI (show_credentials_dialog) requires PySide6.
"""

import os
import json
import logging
from pathlib import Path
from typing import Optional, Dict, Tuple

logger = logging.getLogger(__name__)

# Project base directory
BASE_DIR = Path(__file__).parent.parent.parent
CONFIG_DIR = BASE_DIR / "config"
ENV_FILE = CONFIG_DIR / ".env"
CREDENTIALS_FILE = CONFIG_DIR / "credentials.json"

# Flag to check if PySide6 is available
_PYSIDE6_AVAILABLE = False
try:
    from PySide6 import QtWidgets, QtCore, QtGui
    _PYSIDE6_AVAILABLE = True
except ImportError:
    logger.debug("PySide6 not available - GUI features disabled")
    QtWidgets = None
    QtCore = None
    QtGui = None

# Project base directory
BASE_DIR = Path(__file__).parent.parent.parent
CONFIG_DIR = BASE_DIR / "config"
ENV_FILE = CONFIG_DIR / ".env"
CREDENTIALS_FILE = CONFIG_DIR / "credentials.json"


# =============================================================================
# CREDENTIAL MANAGEMENT FUNCTIONS
# =============================================================================

def get_credentials() -> Dict[str, str]:
    """
    Load saved credentials
    
    Returns:
        Dict with 'server', 'api_key', 'api_user'
    """
    defaults = {
        'server': '',
        'api_key': '',
        'api_user': ''
    }
    
    # Try to load from JSON first (more secure)
    if CREDENTIALS_FILE.exists():
        try:
            with open(CREDENTIALS_FILE, 'r') as f:
                data = json.load(f)
                return {**defaults, **data}
        except Exception as e:
            logger.warning(f"Failed to load credentials.json: {e}")
    
    # Fallback: try .env
    if ENV_FILE.exists():
        try:
            with open(ENV_FILE, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip().strip('"').strip("'")
                        
                        if key == 'FTRACK_SERVER':
                            defaults['server'] = value
                        elif key == 'FTRACK_API_KEY':
                            defaults['api_key'] = value
                        elif key == 'FTRACK_API_USER':
                            defaults['api_user'] = value
        except Exception as e:
            logger.warning(f"Failed to load .env: {e}")
    
    return defaults


def save_credentials(server: str, api_key: str, api_user: str) -> bool:
    """
    Save credentials
    
    Args:
        server: ftrack server URL
        api_key: User's API key
        api_user: Username/email
    
    Returns:
        True if saved successfully
    """
    try:
        # Ensure directory exists
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        
        # Save as JSON (primary)
        credentials = {
            'server': server.strip(),
            'api_key': api_key.strip(),
            'api_user': api_user.strip()
        }
        
        with open(CREDENTIALS_FILE, 'w') as f:
            json.dump(credentials, f, indent=2)
        
        # Also save as .env (compatibility)
        env_content = f'''# ftrack Credentials
# Auto-generated by configuration interface

FTRACK_SERVER="{server.strip()}"
FTRACK_API_KEY="{api_key.strip()}"
FTRACK_API_USER="{api_user.strip()}"
'''
        with open(ENV_FILE, 'w') as f:
            f.write(env_content)
        
        logger.info("Credentials saved successfully")
        return True
        
    except Exception as e:
        logger.error(f"Failed to save credentials: {e}")
        return False


def test_connection(server: str, api_key: str, api_user: str) -> Tuple[bool, str]:
    """
    Test connection with ftrack
    
    Returns:
        Tuple (success: bool, message: str)
    """
    if not server or not api_key or not api_user:
        return False, "All fields are required"
    
    # Validate URL
    if not server.startswith(('http://', 'https://')):
        return False, "Server URL must start with http:// or https://"
    
    try:
        import ftrack_api
        
        # Try to connect
        session = ftrack_api.Session(
            server_url=server.strip(),
            api_key=api_key.strip(),
            api_user=api_user.strip(),
            auto_connect_event_hub=False
        )
        
        # Test with simple project query instead of user query
        try:
            projects = session.query('Project').all()
            project_count = len(projects)
            session.close()
            return True, f"Connected successfully!\n{project_count} projects available"
        except Exception as query_error:
            # If query fails, connection still worked
            session.close()
            return True, f"Connected! (Query test: {str(query_error)[:50]})"
            
    except ImportError:
        # More detailed message about the problem
        import sys
        venv_hint = ""
        project_dir = os.path.expanduser("~/flame_ftrack_integration")
        venv_path = os.path.join(project_dir, ".venv")
        
        if os.path.exists(venv_path):
            venv_hint = (
                f"\n\nVenv found at: {venv_path}"
                "\nTo install ftrack-python-api, run:"
                f"\n  cd {project_dir}"
                "\n  ./setup_environment.sh"
            )
        else:
            venv_hint = (
                f"\n\nTo install dependencies, run:"
                f"\n  cd {project_dir}"
                "\n  ./setup_environment.sh  (creates venv and installs ftrack-python-api)"
                "\n  OR"
                "\n  ./setup_simple.sh  (system-wide installation)"
            )
        
        return False, f"ftrack_api module not installed.{venv_hint}"
    
    except Exception as e:
        error_msg = str(e)
        
        if "401" in error_msg or "Unauthorized" in error_msg:
            return False, "Authentication failed.\nCheck your API key and username."
        elif "404" in error_msg or "Not Found" in error_msg:
            return False, "Server not found.\nCheck the server URL."
        elif "Connection" in error_msg or "timeout" in error_msg.lower():
            return False, "Connection failed.\nCheck your network and server URL."
        else:
            return False, f"Connection failed:\n{error_msg}"


def credentials_are_configured() -> bool:
    """Check if credentials are configured"""
    creds = get_credentials()
    return bool(creds.get('server') and creds.get('api_key') and creds.get('api_user'))


# =============================================================================
# CONFIGURATION DIALOG (requires PySide6)
# =============================================================================

def _check_pyside6():
    """Check if PySide6 is available, raises error if not"""
    if not _PYSIDE6_AVAILABLE:
        raise ImportError(
            "PySide6 is required for GUI features. "
            "This module is available when running inside Flame or with PySide6 installed."
        )

class FtrackCredentialsDialog(QtWidgets.QDialog if _PYSIDE6_AVAILABLE else object):
    """
    Dialog to configure ftrack credentials
    
    Can be used standalone or integrated in Flame.
    Requires PySide6 (available inside Flame 2025+).
    """
    
    def __init__(self, parent=None):
        _check_pyside6()
        super().__init__(parent)
        self._setup_ui()
        self._load_existing()
    
    def _setup_ui(self):
        self.setWindowTitle("ftrack Configuration")
        self.setMinimumWidth(500)
        self.setStyleSheet("""
            QDialog {
                background-color: #313131;
                color: #d9d9d9;
            }
            QLabel {
                color: #d9d9d9;
            }
            QLineEdit {
                background-color: #2a2a2a;
                border: 1px solid #3a3a3a;
                border-radius: 3px;
                padding: 8px;
                color: #d9d9d9;
                font-size: 13px;
            }
            QLineEdit:focus {
                border: 1px solid #4a6fa5;
            }
            QLineEdit:disabled {
                background-color: #252525;
                color: #666666;
            }
            QPushButton {
                background-color: #424142;
                border: none;
                border-radius: 3px;
                padding: 8px 16px;
                color: #d9d9d9;
                font-size: 13px;
            }
            QPushButton:hover {
                background-color: #4a4a4a;
            }
            QPushButton:pressed {
                background-color: #3a3a3a;
            }
            QGroupBox {
                border: 1px solid #3a3a3a;
                border-radius: 5px;
                margin-top: 15px;
                padding-top: 15px;
                font-weight: bold;
                color: #9a9a9a;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px;
            }
        """)
        
        layout = QtWidgets.QVBoxLayout(self)
        layout.setSpacing(15)
        layout.setContentsMargins(20, 20, 20, 20)
        
        # Header
        header_layout = QtWidgets.QHBoxLayout()
        
        # Logo/Icon placeholder
        icon_label = QtWidgets.QLabel("🔗")
        icon_label.setStyleSheet("font-size: 32px;")
        header_layout.addWidget(icon_label)
        
        # Title and description
        title_layout = QtWidgets.QVBoxLayout()
        title = QtWidgets.QLabel("ftrack Connection Setup")
        title.setStyleSheet("font-size: 18px; font-weight: bold; color: #d9d9d9;")
        title_layout.addWidget(title)
        
        subtitle = QtWidgets.QLabel("Configure your ftrack credentials to enable synchronization")
        subtitle.setStyleSheet("font-size: 12px; color: #7a7a7a;")
        title_layout.addWidget(subtitle)
        
        header_layout.addLayout(title_layout)
        header_layout.addStretch()
        layout.addLayout(header_layout)
        
        # Credentials Group
        creds_group = QtWidgets.QGroupBox("Credentials")
        creds_layout = QtWidgets.QFormLayout(creds_group)
        creds_layout.setSpacing(12)
        creds_layout.setContentsMargins(15, 20, 15, 15)
        
        # Server URL
        self.server_edit = QtWidgets.QLineEdit()
        self.server_edit.setPlaceholderText("https://your-studio.ftrackapp.com")
        server_label = QtWidgets.QLabel("Server URL:")
        server_label.setToolTip("The URL of your ftrack server")
        creds_layout.addRow(server_label, self.server_edit)
        
        # API User
        self.user_edit = QtWidgets.QLineEdit()
        self.user_edit.setPlaceholderText("your.email@studio.com")
        user_label = QtWidgets.QLabel("Username:")
        user_label.setToolTip("Your ftrack username (usually your email)")
        creds_layout.addRow(user_label, self.user_edit)
        
        # API Key
        self.key_edit = QtWidgets.QLineEdit()
        self.key_edit.setPlaceholderText("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
        self.key_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        
        key_layout = QtWidgets.QHBoxLayout()
        key_layout.setSpacing(5)
        key_layout.addWidget(self.key_edit)
        
        self.show_key_btn = QtWidgets.QPushButton("👁")
        self.show_key_btn.setFixedWidth(35)
        self.show_key_btn.setToolTip("Show/Hide API Key")
        self.show_key_btn.clicked.connect(self._toggle_key_visibility)
        key_layout.addWidget(self.show_key_btn)
        
        key_label = QtWidgets.QLabel("API Key:")
        key_label.setToolTip("Your personal ftrack API key")
        creds_layout.addRow(key_label, key_layout)
        
        layout.addWidget(creds_group)
        
        # Help text
        help_text = QtWidgets.QLabel(
            "💡 To get your API key:\n"
            "   1. Log in to ftrack\n"
            "   2. Click your avatar → Settings\n"
            "   3. Go to 'API Keys' section\n"
            "   4. Create a new key or copy existing one"
        )
        help_text.setStyleSheet("""
            background-color: #2a3a4a;
            border-radius: 5px;
            padding: 12px;
            color: #9ac;
            font-size: 11px;
        """)
        layout.addWidget(help_text)
        
        # Status
        self.status_label = QtWidgets.QLabel("")
        self.status_label.setStyleSheet("padding: 10px; border-radius: 3px;")
        self.status_label.setVisible(False)
        layout.addWidget(self.status_label)
        
        # Buttons
        button_layout = QtWidgets.QHBoxLayout()
        button_layout.setSpacing(10)
        
        self.test_btn = QtWidgets.QPushButton("🔍 Test Connection")
        self.test_btn.clicked.connect(self._test_connection)
        button_layout.addWidget(self.test_btn)
        
        button_layout.addStretch()
        
        self.clear_btn = QtWidgets.QPushButton("Clear")
        self.clear_btn.clicked.connect(self._clear_fields)
        button_layout.addWidget(self.clear_btn)
        
        self.cancel_btn = QtWidgets.QPushButton("Cancel")
        self.cancel_btn.clicked.connect(self.reject)
        button_layout.addWidget(self.cancel_btn)
        
        self.save_btn = QtWidgets.QPushButton("💾 Save")
        self.save_btn.setStyleSheet("""
            QPushButton {
                background-color: #4a6fa5;
                color: white;
                font-weight: bold;
                padding: 8px 24px;
            }
            QPushButton:hover {
                background-color: #5a7fb5;
            }
        """)
        self.save_btn.clicked.connect(self._save)
        button_layout.addWidget(self.save_btn)
        
        layout.addLayout(button_layout)
    
    def _load_existing(self):
        """Load existing credentials"""
        creds = get_credentials()
        self.server_edit.setText(creds.get('server', ''))
        self.user_edit.setText(creds.get('api_user', ''))
        self.key_edit.setText(creds.get('api_key', ''))
    
    def _toggle_key_visibility(self):
        """Toggle API key visibility"""
        if self.key_edit.echoMode() == QtWidgets.QLineEdit.EchoMode.Password:
            self.key_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
            self.show_key_btn.setText("🔒")
        else:
            self.key_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
            self.show_key_btn.setText("👁")
    
    def _show_status(self, message: str, success: bool):
        """Show status message"""
        if success:
            self.status_label.setStyleSheet("""
                background-color: #2a4a2a;
                border: 1px solid #3a6a3a;
                border-radius: 3px;
                padding: 10px;
                color: #8c8;
            """)
        else:
            self.status_label.setStyleSheet("""
                background-color: #4a2a2a;
                border: 1px solid #6a3a3a;
                border-radius: 3px;
                padding: 10px;
                color: #c88;
            """)
        
        self.status_label.setText(message)
        self.status_label.setVisible(True)
    
    def _test_connection(self):
        """Test connection with ftrack"""
        server = self.server_edit.text()
        api_key = self.key_edit.text()
        api_user = self.user_edit.text()
        
        if not all([server, api_key, api_user]):
            self._show_status("⚠️ Please fill in all fields", False)
            return
        
        # Show loading
        self.test_btn.setEnabled(False)
        self.test_btn.setText("Testing...")
        self.status_label.setText("🔄 Testing connection...")
        self.status_label.setStyleSheet("""
            background-color: #3a3a4a;
            border-radius: 3px;
            padding: 10px;
            color: #99a;
        """)
        self.status_label.setVisible(True)
        
        # Force UI update
        QtWidgets.QApplication.processEvents()
        
        # Test connection
        success, message = test_connection(server, api_key, api_user)
        
        if success:
            self._show_status(f"✅ {message}", True)
        else:
            self._show_status(f"❌ {message}", False)
        
        self.test_btn.setEnabled(True)
        self.test_btn.setText("🔍 Test Connection")
    
    def _clear_fields(self):
        """Clear all fields"""
        self.server_edit.clear()
        self.user_edit.clear()
        self.key_edit.clear()
        self.status_label.setVisible(False)
    
    def _save(self):
        """Save credentials"""
        server = self.server_edit.text()
        api_key = self.key_edit.text()
        api_user = self.user_edit.text()
        
        if not all([server, api_key, api_user]):
            self._show_status("⚠️ Please fill in all fields", False)
            return
        
        if save_credentials(server, api_key, api_user):
            self._show_status("✅ Credentials saved successfully!", True)
            
            # Close after 1 second
            QtCore.QTimer.singleShot(1000, self.accept)
        else:
            self._show_status("❌ Failed to save credentials", False)


# =============================================================================
# FUNCTIONS FOR FLAME INTEGRATION
# =============================================================================

def show_credentials_dialog(parent=None):
    """
    Show configuration dialog
    
    Can be called from anywhere (Flame hook, menu, etc.)
    """
    dialog = FtrackCredentialsDialog(parent)
    return dialog.exec() == QtWidgets.QDialog.DialogCode.Accepted


def get_flame_menu_actions():
    """
    Return actions for Flame menu
    
    Usage in hook:
        def get_main_menu_custom_ui_actions(selection, **kwargs):
            return get_flame_menu_actions()
    """
    return [
        {
            'name': 'ftrack',
            'actions': [
                {
                    'name': 'Configure Credentials...',
                    'execute': lambda sel: show_credentials_dialog()
                },
                {
                    'name': 'Test Connection',
                    'execute': lambda sel: _quick_test_connection()
                }
            ]
        }
    ]


def _quick_test_connection():
    """Quick connection test via menu"""
    from PySide6 import QtWidgets
    
    if not credentials_are_configured():
        QtWidgets.QMessageBox.warning(
            None,
            "ftrack",
            "Credentials not configured.\n\nUse 'Configure Credentials...' first."
        )
        return
    
    creds = get_credentials()
    success, message = test_connection(
        creds['server'],
        creds['api_key'],
        creds['api_user']
    )
    
    if success:
        QtWidgets.QMessageBox.information(None, "ftrack", f"✅ {message}")
    else:
        QtWidgets.QMessageBox.warning(None, "ftrack", f"❌ {message}")


# =============================================================================
# EXPORT
# =============================================================================

__all__ = [
    'get_credentials',
    'save_credentials', 
    'test_connection',
    'credentials_are_configured',
    'FtrackCredentialsDialog',
    'show_credentials_dialog',
    'get_flame_menu_actions'
]


# =============================================================================
# TEST
# =============================================================================

if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    
    dialog = FtrackCredentialsDialog()
    result = dialog.exec()
    
    if result == QtWidgets.QDialog.DialogCode.Accepted:
        print("Credentials saved!")
    else:
        print("Cancelled")
    
    sys.exit(0)
